name = "nerf"
version = "0.4.0"
licences = ["Apache-2.0"]
description = "Gleam bindings to gun, the HTTP/1.1, HTTP/2 and Websocket client"
repository = { type = "github", user = "lpil", repo = "nerf" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
gun = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
certifi = ">= 2.16.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
